Fixes #87
USGS-WiM/SC-RunoffModelingServices pull request #88
Opened 2023-01-09 16:26 UTC by harper-wavra

changed to
=(0.42/SQRT(H19))(H17H16/SQRT(H18/100))^0.8
from
=(0.42/SQRT(H19))(H17H16/SQRT((MAX(0.0001,H18)/100))^0.8)

2023-01-11 21:47 UTC, amedenblik requested changes
The `traveltimetc` endpoint is giving this 500 error: 
```
{
  "detail": "float division by zero"
}
```

Upon further inspection of the spreadsheet, it turns out that the value of the Bermuda grass Overland Slope is not actually 0.00 but 0.000001: 
![image](https://user-images.githubusercontent.com/40237491/211924637-2b1e69c9-db50-478c-a65f-1d844f040695.png)

That is what is preventing the spreadsheet from having a similar "divide by 0" error.

My suggestion is to change the equation to:

~`travel_time_sheet_flow += (0.42 / math.sqrt(P2_24_2)) * (mannings_n*corrected_length/math.sqrt((max(0.000001,surface["Overland Slope"])/100.0))**0.8) # minutes`~

Need to look into this more.

2023-01-13 16:22 UTC, harper-wavra commented
- added Exception if user enters a value for Overland Slope that is less than or eqaul to 0
- changed traveltimetc example request to match new spreadsheet

2023-01-13 17:05 UTC, amedenblik approved these changes

2023-01-13 17:05 UTC, amedenblik commented on CHANGELOG.md
> +-  Exception if user enters a value for Overland Slope that is less than or eqaul to 0
Typo "eqaul"

2023-01-13 17:06 UTC, amedenblik commented on CHANGELOG.md
> +-  Exception if user enters a value for Overland Slope that is less than or eqaul to 0
```suggestion
-  Exception if user enters a value for Overland Slope that is less than or equal to 0
```

2023-01-13 17:07 UTC, merged